"""Emit compact unrolled SIMD op-schedule glue per circuit."""

from __future__ import annotations

from typing import Any

from sparc.deep_compile.codegen_nodes import GraphPlan, emit_schedule_body
from sparc.deep_compile.isa import IsaPlan
from sparc.deep_compile.tape import TapeLayout


def emit_c_source(
    snap: dict[str, Any],
    *,
    isa: IsaPlan,
    parallel: bool = True,
    tile: int = 128,
) -> str:
    """Generate glue .c with unrolled calls into sparc_ultra_rt SIMD primitives."""
    layout = TapeLayout.from_snapshot(snap)
    plan = GraphPlan.from_snapshot(snap)
    n_nodes = layout.n_nodes
    max_var = int(snap["max_var"])
    par_flag = 1 if parallel else 0

    parts: list[str] = [
        "/* Auto-generated by SparC ultra deep_compile (op schedule). Do not edit. */",
        '#include "sparc_ultra_rt.h"',
        "#include <stdint.h>",
        "#include <stdlib.h>",
        "",
    ]

    if parallel:
        parts.extend(
            [
                "#ifdef _OPENMP",
                "#include <omp.h>",
                "#endif",
                "",
            ]
        )

    parts.extend(
        [
            "#ifdef _MSC_VER",
            "#define SPARC_EXPORT __declspec(dllexport)",
            "#else",
            "#define SPARC_EXPORT",
            "#endif",
            "",
            f"#define SPARC_N_NODES {n_nodes}",
            f"#define SPARC_ROOT_INDEX {layout.root_index}",
            f"#define SPARC_MAX_VAR {max_var}",
            f"#define SPARC_TILE_DEFAULT {tile}",
            f"#define SPARC_PARALLEL_DEFAULT {par_flag}",
            f"#define SPARC_ISA_NAME \"{isa.name}\"",
            "",
            f"static const int32_t sparc_identity_col[{max_var + 1}] = {{",
            ", ".join(str(i) for i in range(max_var + 1)),
            "};",
            "",
            "static void sparc_eval_tile(",
            "    int log_space,",
            "    double* tape,",
            "    const int32_t* data,",
            "    int32_t data_stride,",
            "    const int32_t* col_for_var,",
            "    int32_t r0,",
            "    int32_t rn,",
            "    int32_t ws_stride,",
            "    double* workspace",
            ") {",
        ]
    )
    parts.extend(emit_schedule_body(snap, layout, plan))
    parts.append("}")
    parts.append("")
    parts.extend(_emit_batch_impl(parallel))
    parts.extend(_emit_exports(n_nodes))
    return "\n".join(parts)


def _emit_batch_impl(parallel: bool) -> list[str]:
    lines = [
        "static void sparc_eval_batch_impl(",
        "    int log_space,",
        "    double* tape,",
        "    const int32_t* data,",
        "    int32_t data_stride,",
        "    const int32_t* col_for_var,",
        "    int32_t n_rows,",
        "    double* workspace,",
        "    double* out,",
        "    int32_t tile,",
        "    int32_t parallel",
        ") {",
        "  int32_t r0, rn, lr;",
        "  if (tile < 1) tile = SPARC_TILE_DEFAULT;",
    ]
    if parallel:
        lines.extend(
            [
                "#ifdef _OPENMP",
                "  if (parallel) {",
                "#pragma omp parallel",
                "    {",
                "      int32_t tid = omp_get_thread_num();",
                "      double* ws_tile = workspace + (size_t)tid * (size_t)SPARC_N_NODES * (size_t)tile;",
                "#pragma omp for schedule(static)",
                "      for (r0 = 0; r0 < n_rows; r0 += tile) {",
                "        rn = n_rows - r0;",
                "        if (rn > tile) rn = tile;",
                "        sparc_eval_tile(log_space, tape, data, data_stride, col_for_var,",
                "            r0, rn, tile, ws_tile);",
                "        for (lr = 0; lr < rn; ++lr) {",
                "          out[r0 + lr] = ws_tile[(size_t)SPARC_ROOT_INDEX * (size_t)tile + (size_t)lr];",
                "        }",
                "      }",
                "    }",
                "    return;",
                "  }",
                "#endif",
            ]
        )
    lines.extend(
        [
            "  (void)parallel;",
            "  for (r0 = 0; r0 < n_rows; r0 += tile) {",
            "    rn = n_rows - r0;",
            "    if (rn > tile) rn = tile;",
            "    sparc_eval_tile(log_space, tape, data, data_stride, col_for_var,",
            "        r0, rn, tile, workspace);",
            "    for (lr = 0; lr < rn; ++lr) {",
            "      out[r0 + lr] = workspace[(size_t)SPARC_ROOT_INDEX * (size_t)tile + (size_t)lr];",
            "    }",
            "  }",
            "}",
            "",
        ]
    )
    return lines


def _emit_exports(n_nodes: int) -> list[str]:
    lines = [
        "static void sparc_eval_row(",
        "    int log_space,",
        "    double* tape,",
        "    const int32_t* data,",
        "    int32_t data_stride,",
        "    const int32_t* col_for_var,",
        "    double* workspace,",
        "    double* out",
        ") {",
        "  sparc_eval_tile(log_space, tape, data, data_stride, col_for_var,",
        "      0, 1, 1, workspace);",
        "  *out = workspace[(size_t)SPARC_ROOT_INDEX];",
        "}",
        "",
        "SPARC_EXPORT",
        "int32_t sparc_workspace_doubles(int32_t n_nodes, int32_t tile, int32_t parallel) {",
        "  int32_t n_threads = 1;",
        "#ifdef _OPENMP",
        "  if (parallel) n_threads = omp_get_max_threads();",
        "#else",
        "  (void)parallel;",
        "#endif",
        "  return n_nodes * tile * n_threads;",
        "}",
        "",
        "SPARC_EXPORT",
        "const char* sparc_active_isa_name(void) {",
        "  return SPARC_ISA_NAME;",
        "}",
        "",
        "SPARC_EXPORT",
        "double sparc_likelihood_row(double* tape, const int32_t* ev) {",
    ]
    if n_nodes > 8192:
        lines.extend(
            [
                "  double* workspace = (double*)malloc((size_t)SPARC_N_NODES * sizeof(double));",
                "  double out;",
                "  if (workspace == NULL) return 0.0;",
                "  sparc_eval_row(0, tape, ev, 1, sparc_identity_col, workspace, &out);",
                "  free(workspace);",
                "  return out;",
            ]
        )
    else:
        lines.extend(
            [
                "  double workspace[SPARC_N_NODES];",
                "  double out;",
                "  sparc_eval_row(0, tape, ev, 1, sparc_identity_col, workspace, &out);",
                "  return out;",
            ]
        )
    lines.extend(
        [
            "}",
            "",
            "SPARC_EXPORT",
            "double sparc_log_likelihood_row(double* tape, const int32_t* ev) {",
        ]
    )
    if n_nodes > 8192:
        lines.extend(
            [
                "  double* workspace = (double*)malloc((size_t)SPARC_N_NODES * sizeof(double));",
                "  double out;",
                "  if (workspace == NULL) return SPARC_NEG_INF;",
                "  sparc_eval_row(1, tape, ev, 1, sparc_identity_col, workspace, &out);",
                "  free(workspace);",
                "  return out;",
            ]
        )
    else:
        lines.extend(
            [
                "  double workspace[SPARC_N_NODES];",
                "  double out;",
                "  sparc_eval_row(1, tape, ev, 1, sparc_identity_col, workspace, &out);",
                "  return out;",
            ]
        )
    lines.extend(
        [
            "}",
            "",
            "SPARC_EXPORT",
            "void sparc_likelihood_batch(",
            "    double* tape,",
            "    const int32_t* data,",
            "    int32_t data_stride,",
            "    const int32_t* col_for_var,",
            "    int32_t n_rows,",
            "    double* workspace,",
            "    double* out,",
            "    int32_t tile,",
            "    int32_t parallel",
            ") {",
            "  sparc_eval_batch_impl(0, tape, data, data_stride, col_for_var,",
            "      n_rows, workspace, out, tile, parallel);",
            "}",
            "",
            "SPARC_EXPORT",
            "void sparc_log_likelihood_batch(",
            "    double* tape,",
            "    const int32_t* data,",
            "    int32_t data_stride,",
            "    const int32_t* col_for_var,",
            "    int32_t n_rows,",
            "    double* workspace,",
            "    double* out,",
            "    int32_t tile,",
            "    int32_t parallel",
            ") {",
            "  sparc_eval_batch_impl(1, tape, data, data_stride, col_for_var,",
            "      n_rows, workspace, out, tile, parallel);",
            "}",
            "",
        ]
    )
    return lines
